#!/bin/bash

echo >&2 Remote helper started with command line \'$@\'
echo >&2 Remote url is passed in second argument: $2

repo_path=$HOME/coding/grh/remotes/$(echo $2 | sed 's/.*:\/\///')

echo >&2 Using remote repository path $repo_path. Running the communication loop
while :; do
    read line

    if [ -z "$line" ]; then
        echo >&2 Input command line is empty. Communication done
        exit 0
    fi

    command=$(echo $line | cut -d" " -f1)
    arg=$(echo $line | cut -d" " -f2)

    echo >&2 Handling input command $command with argument $arg

    case "$command" in
    "capabilities")
        echo connect
        echo
        ;;
    "connect")
        echo
        echo >&2 Running helper utility $arg on repository $repo_path
        $arg $repo_path
        ;;
    esac

done
